language: c
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_miniconda.sh

before_script:
    - conda create -q -y --name testenv python=$CONDA_PY
    - source activate testenv
    - conda build -c bioconda --python $CONDA_PY ./devtools/conda-recipe/  # Build the conda recipe for the latest dev
    - conda install -c bioconda --use-local -yq cnvkit  # Install the locally built package and its requirements
    - conda install -c bioconda -yq pandas==$PANDAS pysam==$PYSAM  # Install the versions desired for testing
    - conda remove cnvkit -y -q  # Remove the conda cnvkit package but keep the dependencies installed
    - python setup.py install  # Install directly from source
    - cd test/
    # For codecov.io
    - pip install codecov

script:
    - coverage run test_io.py
    - coverage run -a test_genome.py
    - coverage run -a test_cnvlib.py
    - coverage run -a test_r.py

after_success:
    - coverage report
    - codecov

os:
  # - osx
  - linux

env:
  - CONDA_PY=2.7 PANDAS=0.18.1 PYSAM=0.10.0
  - CONDA_PY=2.7 PANDAS=0.22.0 PYSAM=0.13.0
  - CONDA_PY=3.5 PANDAS=0.18.1 PYSAM=0.10.0
  - CONDA_PY=3.5 PANDAS=0.22.0 PYSAM=0.13.0
